// GENERATED FILE - do not hand-edit. Regenerate with the collector in
// research/scripts/ if the base location or the source data changes.
//
// Every number here is measured, not written:
//   miles       driving distance from our base ZIP 91748 (Rowland Heights),
//               via OSRM road routing
//   travelFee   that distance under our published policy: first 50 miles free,
//               then $1 for each mile beyond
//   months      2019-2024 daily observations from the Open-Meteo historical
//               archive, averaged by month. rainPct is the share of days with
//               at least 0.04 in of precipitation. sunset is real local sunset.
//
// The point of this file is that no competitor can copy it: it is our base,
// our travel policy, and six years of weather for the exact place we cook.

export type CityMonth = {
  month: string
  high: number
  low: number
  rainPct: number
  sunset: string
}

export type CityClimate = {
  miles: number
  travelFee: number
  bestEvening: string
  bestLunch: string
  hotMonths: string
  wettestMonth: string
  wettestPct: number
  latestSunset: string
  latestSunsetMonth: string
  julyHigh: number
  januaryHigh: number
  months: CityMonth[]
}

export const cityClimate: Record<string, CityClimate> = {
  "anaheim": {
    miles: 11.9,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 30,
    latestSunset: "8:04pm",
    latestSunsetMonth: "June",
    julyHigh: 85,
    januaryHigh: 66,
    months: [
      { month: "Jan", high: 66, low: 47, rainPct: 18, sunset: "6:06pm" },
      { month: "Feb", high: 66, low: 47, rainPct: 21, sunset: "6:35pm" },
      { month: "Mar", high: 66, low: 49, rainPct: 30, sunset: "7:00pm" },
      { month: "Apr", high: 73, low: 53, rainPct: 9, sunset: "7:23pm" },
      { month: "May", high: 74, low: 56, rainPct: 6, sunset: "7:46pm" },
      { month: "Jun", high: 80, low: 59, rainPct: 1, sunset: "8:04pm" },
      { month: "Jul", high: 85, low: 63, rainPct: 1, sunset: "8:02pm" },
      { month: "Aug", high: 87, low: 65, rainPct: 2, sunset: "7:36pm" },
      { month: "Sep", high: 86, low: 64, rainPct: 6, sunset: "6:57pm" },
      { month: "Oct", high: 81, low: 59, rainPct: 4, sunset: "6:16pm" },
      { month: "Nov", high: 74, low: 53, rainPct: 9, sunset: "5:47pm" },
      { month: "Dec", high: 66, low: 49, rainPct: 17, sunset: "5:44pm" },
    ],
  },
  "arcadia": {
    miles: 24.5,
    travelFee: 0,
    bestEvening: "June through October",
    bestLunch: "June and October",
    hotMonths: "August",
    wettestMonth: "March",
    wettestPct: 36,
    latestSunset: "8:05pm",
    latestSunsetMonth: "June",
    julyHigh: 92,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 45, rainPct: 20, sunset: "6:06pm" },
      { month: "Feb", high: 65, low: 44, rainPct: 24, sunset: "6:35pm" },
      { month: "Mar", high: 66, low: 46, rainPct: 36, sunset: "7:01pm" },
      { month: "Apr", high: 74, low: 51, rainPct: 18, sunset: "7:24pm" },
      { month: "May", high: 77, low: 54, rainPct: 13, sunset: "7:48pm" },
      { month: "Jun", high: 84, low: 60, rainPct: 4, sunset: "8:05pm" },
      { month: "Jul", high: 92, low: 65, rainPct: 1, sunset: "8:03pm" },
      { month: "Aug", high: 93, low: 67, rainPct: 3, sunset: "7:37pm" },
      { month: "Sep", high: 90, low: 65, rainPct: 9, sunset: "6:57pm" },
      { month: "Oct", high: 83, low: 58, rainPct: 7, sunset: "6:16pm" },
      { month: "Nov", high: 74, low: 50, rainPct: 13, sunset: "5:48pm" },
      { month: "Dec", high: 65, low: 46, rainPct: 22, sunset: "5:44pm" },
    ],
  },
  "beverly-hills": {
    miles: 34.3,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 28,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 85,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 45, rainPct: 18, sunset: "6:08pm" },
      { month: "Feb", high: 66, low: 45, rainPct: 18, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 47, rainPct: 28, sunset: "7:02pm" },
      { month: "Apr", high: 73, low: 51, rainPct: 8, sunset: "7:25pm" },
      { month: "May", high: 74, low: 54, rainPct: 7, sunset: "7:49pm" },
      { month: "Jun", high: 80, low: 59, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 85, low: 61, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 87, low: 63, rainPct: 3, sunset: "7:39pm" },
      { month: "Sep", high: 86, low: 62, rainPct: 6, sunset: "6:59pm" },
      { month: "Oct", high: 82, low: 57, rainPct: 3, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 49, rainPct: 8, sunset: "5:49pm" },
      { month: "Dec", high: 66, low: 46, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "burbank": {
    miles: 34.7,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 33,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 90,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 47, rainPct: 21, sunset: "6:07pm" },
      { month: "Feb", high: 65, low: 47, rainPct: 21, sunset: "6:36pm" },
      { month: "Mar", high: 66, low: 48, rainPct: 33, sunset: "7:02pm" },
      { month: "Apr", high: 74, low: 53, rainPct: 16, sunset: "7:25pm" },
      { month: "May", high: 76, low: 55, rainPct: 11, sunset: "7:49pm" },
      { month: "Jun", high: 83, low: 61, rainPct: 6, sunset: "8:06pm" },
      { month: "Jul", high: 90, low: 66, rainPct: 1, sunset: "8:05pm" },
      { month: "Aug", high: 92, low: 68, rainPct: 3, sunset: "7:39pm" },
      { month: "Sep", high: 89, low: 67, rainPct: 8, sunset: "6:58pm" },
      { month: "Oct", high: 83, low: 61, rainPct: 6, sunset: "6:17pm" },
      { month: "Nov", high: 73, low: 53, rainPct: 9, sunset: "5:48pm" },
      { month: "Dec", high: 65, low: 49, rainPct: 20, sunset: "5:45pm" },
    ],
  },
  "corona": {
    miles: 27.1,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through May and November",
    hotMonths: "July through August",
    wettestMonth: "March",
    wettestPct: 26,
    latestSunset: "8:03pm",
    latestSunsetMonth: "June",
    julyHigh: 93,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 46, rainPct: 19, sunset: "6:05pm" },
      { month: "Feb", high: 66, low: 46, rainPct: 22, sunset: "6:34pm" },
      { month: "Mar", high: 67, low: 47, rainPct: 26, sunset: "6:59pm" },
      { month: "Apr", high: 75, low: 52, rainPct: 7, sunset: "7:22pm" },
      { month: "May", high: 78, low: 55, rainPct: 6, sunset: "7:45pm" },
      { month: "Jun", high: 86, low: 60, rainPct: 0, sunset: "8:03pm" },
      { month: "Jul", high: 93, low: 64, rainPct: 1, sunset: "8:01pm" },
      { month: "Aug", high: 94, low: 66, rainPct: 3, sunset: "7:35pm" },
      { month: "Sep", high: 91, low: 65, rainPct: 6, sunset: "6:56pm" },
      { month: "Oct", high: 85, low: 59, rainPct: 4, sunset: "6:15pm" },
      { month: "Nov", high: 75, low: 51, rainPct: 9, sunset: "5:46pm" },
      { month: "Dec", high: 67, low: 47, rainPct: 17, sunset: "5:43pm" },
    ],
  },
  "culver-city": {
    miles: 33.3,
    travelFee: 0,
    bestEvening: "June through October",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 25,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 76,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 46, rainPct: 19, sunset: "6:08pm" },
      { month: "Feb", high: 63, low: 46, rainPct: 20, sunset: "6:37pm" },
      { month: "Mar", high: 63, low: 48, rainPct: 25, sunset: "7:02pm" },
      { month: "Apr", high: 67, low: 52, rainPct: 7, sunset: "7:25pm" },
      { month: "May", high: 67, low: 56, rainPct: 4, sunset: "7:49pm" },
      { month: "Jun", high: 72, low: 60, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 76, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 78, low: 64, rainPct: 2, sunset: "7:39pm" },
      { month: "Sep", high: 78, low: 63, rainPct: 5, sunset: "6:59pm" },
      { month: "Oct", high: 75, low: 57, rainPct: 1, sunset: "6:18pm" },
      { month: "Nov", high: 69, low: 50, rainPct: 8, sunset: "5:49pm" },
      { month: "Dec", high: 63, low: 47, rainPct: 19, sunset: "5:46pm" },
    ],
  },
  "diamond-bar": {
    miles: 7.3,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May and October through November",
    hotMonths: "August",
    wettestMonth: "March",
    wettestPct: 31,
    latestSunset: "8:04pm",
    latestSunsetMonth: "June",
    julyHigh: 92,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 46, rainPct: 20, sunset: "6:05pm" },
      { month: "Feb", high: 65, low: 45, rainPct: 24, sunset: "6:34pm" },
      { month: "Mar", high: 66, low: 47, rainPct: 31, sunset: "7:00pm" },
      { month: "Apr", high: 74, low: 52, rainPct: 13, sunset: "7:23pm" },
      { month: "May", high: 77, low: 54, rainPct: 10, sunset: "7:46pm" },
      { month: "Jun", high: 85, low: 58, rainPct: 3, sunset: "8:04pm" },
      { month: "Jul", high: 92, low: 63, rainPct: 1, sunset: "8:02pm" },
      { month: "Aug", high: 94, low: 65, rainPct: 3, sunset: "7:36pm" },
      { month: "Sep", high: 90, low: 64, rainPct: 7, sunset: "6:56pm" },
      { month: "Oct", high: 83, low: 59, rainPct: 6, sunset: "6:15pm" },
      { month: "Nov", high: 74, low: 51, rainPct: 11, sunset: "5:47pm" },
      { month: "Dec", high: 65, low: 47, rainPct: 20, sunset: "5:43pm" },
    ],
  },
  "downtown-los-angeles": {
    miles: 24.7,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 29,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 88,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 46, rainPct: 19, sunset: "6:07pm" },
      { month: "Feb", high: 67, low: 46, rainPct: 18, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 48, rainPct: 29, sunset: "7:01pm" },
      { month: "Apr", high: 74, low: 52, rainPct: 10, sunset: "7:25pm" },
      { month: "May", high: 76, low: 55, rainPct: 9, sunset: "7:48pm" },
      { month: "Jun", high: 82, low: 60, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 88, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 89, low: 64, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 6, sunset: "6:58pm" },
      { month: "Oct", high: 83, low: 59, rainPct: 4, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 51, rainPct: 7, sunset: "5:48pm" },
      { month: "Dec", high: 66, low: 47, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "glendale": {
    miles: 33.0,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 33,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 89,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 47, rainPct: 20, sunset: "6:07pm" },
      { month: "Feb", high: 66, low: 46, rainPct: 22, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 48, rainPct: 33, sunset: "7:01pm" },
      { month: "Apr", high: 74, low: 52, rainPct: 13, sunset: "7:25pm" },
      { month: "May", high: 76, low: 54, rainPct: 9, sunset: "7:49pm" },
      { month: "Jun", high: 83, low: 59, rainPct: 5, sunset: "8:06pm" },
      { month: "Jul", high: 89, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 91, low: 64, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 7, sunset: "6:58pm" },
      { month: "Oct", high: 83, low: 59, rainPct: 5, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 52, rainPct: 11, sunset: "5:48pm" },
      { month: "Dec", high: 65, low: 48, rainPct: 20, sunset: "5:45pm" },
    ],
  },
  "hollywood": {
    miles: 30.8,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 28,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 85,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 45, rainPct: 18, sunset: "6:08pm" },
      { month: "Feb", high: 66, low: 45, rainPct: 18, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 47, rainPct: 28, sunset: "7:02pm" },
      { month: "Apr", high: 73, low: 51, rainPct: 8, sunset: "7:25pm" },
      { month: "May", high: 74, low: 54, rainPct: 7, sunset: "7:49pm" },
      { month: "Jun", high: 80, low: 59, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 85, low: 61, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 87, low: 63, rainPct: 3, sunset: "7:39pm" },
      { month: "Sep", high: 86, low: 62, rainPct: 6, sunset: "6:59pm" },
      { month: "Oct", high: 82, low: 57, rainPct: 3, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 49, rainPct: 8, sunset: "5:49pm" },
      { month: "Dec", high: 66, low: 46, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "huntington-beach": {
    miles: 29.8,
    travelFee: 0,
    bestEvening: "June through October",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 25,
    latestSunset: "8:04pm",
    latestSunsetMonth: "June",
    julyHigh: 76,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 47, rainPct: 19, sunset: "6:07pm" },
      { month: "Feb", high: 64, low: 47, rainPct: 18, sunset: "6:35pm" },
      { month: "Mar", high: 63, low: 49, rainPct: 25, sunset: "7:00pm" },
      { month: "Apr", high: 68, low: 53, rainPct: 7, sunset: "7:23pm" },
      { month: "May", high: 69, low: 56, rainPct: 6, sunset: "7:46pm" },
      { month: "Jun", high: 73, low: 60, rainPct: 2, sunset: "8:04pm" },
      { month: "Jul", high: 76, low: 62, rainPct: 1, sunset: "8:02pm" },
      { month: "Aug", high: 78, low: 63, rainPct: 3, sunset: "7:36pm" },
      { month: "Sep", high: 79, low: 63, rainPct: 6, sunset: "6:57pm" },
      { month: "Oct", high: 76, low: 58, rainPct: 3, sunset: "6:16pm" },
      { month: "Nov", high: 70, low: 52, rainPct: 7, sunset: "5:48pm" },
      { month: "Dec", high: 64, low: 48, rainPct: 18, sunset: "5:45pm" },
    ],
  },
  "inglewood": {
    miles: 36.8,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 24,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 83,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 45, rainPct: 19, sunset: "6:08pm" },
      { month: "Feb", high: 66, low: 45, rainPct: 19, sunset: "6:36pm" },
      { month: "Mar", high: 66, low: 48, rainPct: 24, sunset: "7:02pm" },
      { month: "Apr", high: 72, low: 52, rainPct: 8, sunset: "7:25pm" },
      { month: "May", high: 73, low: 56, rainPct: 4, sunset: "7:48pm" },
      { month: "Jun", high: 78, low: 60, rainPct: 1, sunset: "8:06pm" },
      { month: "Jul", high: 83, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 84, low: 64, rainPct: 2, sunset: "7:38pm" },
      { month: "Sep", high: 84, low: 63, rainPct: 5, sunset: "6:58pm" },
      { month: "Oct", high: 80, low: 57, rainPct: 2, sunset: "6:17pm" },
      { month: "Nov", high: 73, low: 49, rainPct: 7, sunset: "5:49pm" },
      { month: "Dec", high: 66, low: 46, rainPct: 19, sunset: "5:46pm" },
    ],
  },
  "irvine": {
    miles: 26.7,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through July and September through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 29,
    latestSunset: "8:03pm",
    latestSunsetMonth: "June",
    julyHigh: 83,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 47, rainPct: 18, sunset: "6:06pm" },
      { month: "Feb", high: 66, low: 47, rainPct: 22, sunset: "6:35pm" },
      { month: "Mar", high: 66, low: 49, rainPct: 29, sunset: "7:00pm" },
      { month: "Apr", high: 72, low: 53, rainPct: 11, sunset: "7:23pm" },
      { month: "May", high: 73, low: 55, rainPct: 8, sunset: "7:46pm" },
      { month: "Jun", high: 78, low: 59, rainPct: 4, sunset: "8:03pm" },
      { month: "Jul", high: 83, low: 61, rainPct: 1, sunset: "8:01pm" },
      { month: "Aug", high: 85, low: 63, rainPct: 3, sunset: "7:36pm" },
      { month: "Sep", high: 84, low: 63, rainPct: 4, sunset: "6:56pm" },
      { month: "Oct", high: 80, low: 58, rainPct: 4, sunset: "6:16pm" },
      { month: "Nov", high: 73, low: 52, rainPct: 8, sunset: "5:47pm" },
      { month: "Dec", high: 66, low: 48, rainPct: 17, sunset: "5:44pm" },
    ],
  },
  "long-beach": {
    miles: 30.6,
    travelFee: 0,
    bestEvening: "June through October",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 23,
    latestSunset: "8:05pm",
    latestSunsetMonth: "June",
    julyHigh: 78,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 46, rainPct: 19, sunset: "6:08pm" },
      { month: "Feb", high: 64, low: 46, rainPct: 16, sunset: "6:36pm" },
      { month: "Mar", high: 64, low: 49, rainPct: 23, sunset: "7:01pm" },
      { month: "Apr", high: 68, low: 53, rainPct: 7, sunset: "7:24pm" },
      { month: "May", high: 69, low: 57, rainPct: 4, sunset: "7:47pm" },
      { month: "Jun", high: 74, low: 60, rainPct: 1, sunset: "8:05pm" },
      { month: "Jul", high: 78, low: 63, rainPct: 1, sunset: "8:03pm" },
      { month: "Aug", high: 80, low: 64, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 80, low: 63, rainPct: 6, sunset: "6:58pm" },
      { month: "Oct", high: 77, low: 58, rainPct: 3, sunset: "6:17pm" },
      { month: "Nov", high: 70, low: 51, rainPct: 7, sunset: "5:49pm" },
      { month: "Dec", high: 64, low: 47, rainPct: 18, sunset: "5:46pm" },
    ],
  },
  "los-angeles": {
    miles: 24.9,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 29,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 88,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 46, rainPct: 19, sunset: "6:07pm" },
      { month: "Feb", high: 67, low: 46, rainPct: 18, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 48, rainPct: 29, sunset: "7:01pm" },
      { month: "Apr", high: 74, low: 52, rainPct: 10, sunset: "7:25pm" },
      { month: "May", high: 76, low: 55, rainPct: 9, sunset: "7:48pm" },
      { month: "Jun", high: 82, low: 60, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 88, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 89, low: 64, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 6, sunset: "6:58pm" },
      { month: "Oct", high: 83, low: 59, rainPct: 4, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 51, rainPct: 7, sunset: "5:48pm" },
      { month: "Dec", high: 66, low: 47, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "malibu": {
    miles: 51.0,
    travelFee: 1,
    bestEvening: "June through November",
    bestLunch: "April through July and September through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 29,
    latestSunset: "8:08pm",
    latestSunsetMonth: "June",
    julyHigh: 83,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 50, rainPct: 18, sunset: "6:09pm" },
      { month: "Feb", high: 65, low: 49, rainPct: 20, sunset: "6:38pm" },
      { month: "Mar", high: 65, low: 50, rainPct: 29, sunset: "7:03pm" },
      { month: "Apr", high: 70, low: 54, rainPct: 8, sunset: "7:26pm" },
      { month: "May", high: 71, low: 56, rainPct: 6, sunset: "7:50pm" },
      { month: "Jun", high: 77, low: 61, rainPct: 3, sunset: "8:08pm" },
      { month: "Jul", high: 83, low: 64, rainPct: 1, sunset: "8:06pm" },
      { month: "Aug", high: 85, low: 66, rainPct: 3, sunset: "7:40pm" },
      { month: "Sep", high: 83, low: 65, rainPct: 7, sunset: "7:00pm" },
      { month: "Oct", high: 79, low: 61, rainPct: 3, sunset: "6:19pm" },
      { month: "Nov", high: 72, low: 55, rainPct: 9, sunset: "5:50pm" },
      { month: "Dec", high: 66, low: 51, rainPct: 20, sunset: "5:47pm" },
    ],
  },
  "newport-beach": {
    miles: 31.2,
    travelFee: 0,
    bestEvening: "July through October",
    bestLunch: "May through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 30,
    latestSunset: "8:03pm",
    latestSunsetMonth: "June",
    julyHigh: 74,
    januaryHigh: 62,
    months: [
      { month: "Jan", high: 62, low: 48, rainPct: 19, sunset: "6:07pm" },
      { month: "Feb", high: 62, low: 48, rainPct: 24, sunset: "6:35pm" },
      { month: "Mar", high: 62, low: 50, rainPct: 30, sunset: "7:00pm" },
      { month: "Apr", high: 65, low: 54, rainPct: 12, sunset: "7:23pm" },
      { month: "May", high: 67, low: 57, rainPct: 9, sunset: "7:46pm" },
      { month: "Jun", high: 71, low: 61, rainPct: 3, sunset: "8:03pm" },
      { month: "Jul", high: 74, low: 63, rainPct: 1, sunset: "8:02pm" },
      { month: "Aug", high: 76, low: 64, rainPct: 3, sunset: "7:36pm" },
      { month: "Sep", high: 76, low: 64, rainPct: 6, sunset: "6:57pm" },
      { month: "Oct", high: 73, low: 59, rainPct: 5, sunset: "6:16pm" },
      { month: "Nov", high: 68, low: 53, rainPct: 9, sunset: "5:48pm" },
      { month: "Dec", high: 63, low: 49, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "oceanside": {
    miles: 70.1,
    travelFee: 20,
    bestEvening: "July through October",
    bestLunch: "May through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 34,
    latestSunset: "8:00pm",
    latestSunsetMonth: "June",
    julyHigh: 73,
    januaryHigh: 62,
    months: [
      { month: "Jan", high: 62, low: 48, rainPct: 19, sunset: "6:06pm" },
      { month: "Feb", high: 61, low: 48, rainPct: 26, sunset: "6:34pm" },
      { month: "Mar", high: 61, low: 50, rainPct: 34, sunset: "6:58pm" },
      { month: "Apr", high: 64, low: 54, rainPct: 14, sunset: "7:20pm" },
      { month: "May", high: 66, low: 57, rainPct: 11, sunset: "7:43pm" },
      { month: "Jun", high: 69, low: 61, rainPct: 4, sunset: "8:00pm" },
      { month: "Jul", high: 73, low: 65, rainPct: 2, sunset: "7:58pm" },
      { month: "Aug", high: 75, low: 66, rainPct: 2, sunset: "7:33pm" },
      { month: "Sep", high: 76, low: 65, rainPct: 6, sunset: "6:54pm" },
      { month: "Oct", high: 73, low: 60, rainPct: 6, sunset: "6:14pm" },
      { month: "Nov", high: 68, low: 53, rainPct: 12, sunset: "5:47pm" },
      { month: "Dec", high: 63, low: 49, rainPct: 18, sunset: "5:44pm" },
    ],
  },
  "palm-springs": {
    miles: 86.6,
    travelFee: 37,
    bestEvening: "April through May and October through November",
    bestLunch: "November through February",
    hotMonths: "June through September",
    wettestMonth: "March",
    wettestPct: 13,
    latestSunset: "7:58pm",
    latestSunsetMonth: "June",
    julyHigh: 108,
    januaryHigh: 66,
    months: [
      { month: "Jan", high: 66, low: 49, rainPct: 12, sunset: "6:00pm" },
      { month: "Feb", high: 68, low: 49, rainPct: 11, sunset: "6:29pm" },
      { month: "Mar", high: 72, low: 52, rainPct: 13, sunset: "6:54pm" },
      { month: "Apr", high: 85, low: 61, rainPct: 3, sunset: "7:17pm" },
      { month: "May", high: 91, low: 67, rainPct: 1, sunset: "7:41pm" },
      { month: "Jun", high: 101, low: 77, rainPct: 0, sunset: "7:58pm" },
      { month: "Jul", high: 108, low: 85, rainPct: 1, sunset: "7:56pm" },
      { month: "Aug", high: 106, low: 83, rainPct: 2, sunset: "7:31pm" },
      { month: "Sep", high: 99, low: 76, rainPct: 3, sunset: "6:51pm" },
      { month: "Oct", high: 88, low: 65, rainPct: 2, sunset: "6:10pm" },
      { month: "Nov", high: 75, low: 54, rainPct: 4, sunset: "5:42pm" },
      { month: "Dec", high: 67, low: 50, rainPct: 8, sunset: "5:38pm" },
    ],
  },
  "pasadena": {
    miles: 24.8,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 34,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 89,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 46, rainPct: 20, sunset: "6:07pm" },
      { month: "Feb", high: 65, low: 45, rainPct: 21, sunset: "6:36pm" },
      { month: "Mar", high: 65, low: 46, rainPct: 34, sunset: "7:01pm" },
      { month: "Apr", high: 73, low: 50, rainPct: 15, sunset: "7:24pm" },
      { month: "May", high: 75, low: 53, rainPct: 10, sunset: "7:48pm" },
      { month: "Jun", high: 82, low: 58, rainPct: 4, sunset: "8:06pm" },
      { month: "Jul", high: 89, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 90, low: 65, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 8, sunset: "6:58pm" },
      { month: "Oct", high: 82, low: 58, rainPct: 6, sunset: "6:17pm" },
      { month: "Nov", high: 73, low: 51, rainPct: 12, sunset: "5:48pm" },
      { month: "Dec", high: 64, low: 47, rainPct: 20, sunset: "5:45pm" },
    ],
  },
  "riverside": {
    miles: 33.9,
    travelFee: 0,
    bestEvening: "April through June and September through November",
    bestLunch: "April through May and November",
    hotMonths: "July through September",
    wettestMonth: "March",
    wettestPct: 30,
    latestSunset: "8:02pm",
    latestSunsetMonth: "June",
    julyHigh: 96,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 44, rainPct: 18, sunset: "6:04pm" },
      { month: "Feb", high: 66, low: 44, rainPct: 24, sunset: "6:33pm" },
      { month: "Mar", high: 67, low: 47, rainPct: 30, sunset: "6:58pm" },
      { month: "Apr", high: 76, low: 51, rainPct: 9, sunset: "7:21pm" },
      { month: "May", high: 80, low: 54, rainPct: 8, sunset: "7:45pm" },
      { month: "Jun", high: 88, low: 60, rainPct: 2, sunset: "8:02pm" },
      { month: "Jul", high: 96, low: 64, rainPct: 1, sunset: "8:00pm" },
      { month: "Aug", high: 97, low: 66, rainPct: 2, sunset: "7:35pm" },
      { month: "Sep", high: 93, low: 65, rainPct: 7, sunset: "6:55pm" },
      { month: "Oct", high: 85, low: 57, rainPct: 4, sunset: "6:14pm" },
      { month: "Nov", high: 75, low: 49, rainPct: 9, sunset: "5:45pm" },
      { month: "Dec", high: 66, low: 45, rainPct: 18, sunset: "5:42pm" },
    ],
  },
  "rowland-heights": {
    miles: 0.0,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 28,
    latestSunset: "8:04pm",
    latestSunsetMonth: "June",
    julyHigh: 89,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 45, rainPct: 21, sunset: "6:06pm" },
      { month: "Feb", high: 65, low: 45, rainPct: 22, sunset: "6:35pm" },
      { month: "Mar", high: 65, low: 47, rainPct: 28, sunset: "7:00pm" },
      { month: "Apr", high: 73, low: 51, rainPct: 13, sunset: "7:23pm" },
      { month: "May", high: 76, low: 54, rainPct: 8, sunset: "7:47pm" },
      { month: "Jun", high: 83, low: 58, rainPct: 2, sunset: "8:04pm" },
      { month: "Jul", high: 89, low: 61, rainPct: 1, sunset: "8:02pm" },
      { month: "Aug", high: 91, low: 63, rainPct: 2, sunset: "7:36pm" },
      { month: "Sep", high: 88, low: 62, rainPct: 8, sunset: "6:57pm" },
      { month: "Oct", high: 82, low: 57, rainPct: 3, sunset: "6:16pm" },
      { month: "Nov", high: 73, low: 50, rainPct: 9, sunset: "5:47pm" },
      { month: "Dec", high: 65, low: 46, rainPct: 18, sunset: "5:44pm" },
    ],
  },
  "san-diego": {
    miles: 107.2,
    travelFee: 57,
    bestEvening: "June through October",
    bestLunch: "May through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 32,
    latestSunset: "7:58pm",
    latestSunsetMonth: "June",
    julyHigh: 75,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 47, rainPct: 22, sunset: "6:06pm" },
      { month: "Feb", high: 63, low: 47, rainPct: 21, sunset: "6:33pm" },
      { month: "Mar", high: 63, low: 50, rainPct: 32, sunset: "6:57pm" },
      { month: "Apr", high: 66, low: 54, rainPct: 13, sunset: "7:19pm" },
      { month: "May", high: 68, low: 57, rainPct: 9, sunset: "7:41pm" },
      { month: "Jun", high: 72, low: 61, rainPct: 2, sunset: "7:58pm" },
      { month: "Jul", high: 75, low: 64, rainPct: 1, sunset: "7:56pm" },
      { month: "Aug", high: 78, low: 66, rainPct: 2, sunset: "7:32pm" },
      { month: "Sep", high: 78, low: 65, rainPct: 3, sunset: "6:53pm" },
      { month: "Oct", high: 75, low: 59, rainPct: 6, sunset: "6:14pm" },
      { month: "Nov", high: 70, low: 51, rainPct: 11, sunset: "5:47pm" },
      { month: "Dec", high: 64, low: 48, rainPct: 17, sunset: "5:44pm" },
    ],
  },
  "san-gabriel": {
    miles: 18.3,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 27,
    latestSunset: "8:05pm",
    latestSunsetMonth: "June",
    julyHigh: 89,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 46, rainPct: 19, sunset: "6:07pm" },
      { month: "Feb", high: 66, low: 46, rainPct: 19, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 48, rainPct: 27, sunset: "7:01pm" },
      { month: "Apr", high: 75, low: 52, rainPct: 11, sunset: "7:24pm" },
      { month: "May", high: 76, low: 55, rainPct: 6, sunset: "7:48pm" },
      { month: "Jun", high: 83, low: 59, rainPct: 3, sunset: "8:05pm" },
      { month: "Jul", high: 89, low: 63, rainPct: 1, sunset: "8:03pm" },
      { month: "Aug", high: 90, low: 64, rainPct: 3, sunset: "7:38pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 7, sunset: "6:58pm" },
      { month: "Oct", high: 83, low: 58, rainPct: 3, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 51, rainPct: 7, sunset: "5:48pm" },
      { month: "Dec", high: 66, low: 47, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "santa-clarita": {
    miles: 58.9,
    travelFee: 9,
    bestEvening: "April through October",
    bestLunch: "April through May and October through November",
    hotMonths: "July through August",
    wettestMonth: "March",
    wettestPct: 29,
    latestSunset: "8:08pm",
    latestSunsetMonth: "June",
    julyHigh: 95,
    januaryHigh: 61,
    months: [
      { month: "Jan", high: 61, low: 43, rainPct: 18, sunset: "6:08pm" },
      { month: "Feb", high: 62, low: 43, rainPct: 21, sunset: "6:37pm" },
      { month: "Mar", high: 64, low: 45, rainPct: 29, sunset: "7:02pm" },
      { month: "Apr", high: 74, low: 51, rainPct: 12, sunset: "7:26pm" },
      { month: "May", high: 78, low: 54, rainPct: 9, sunset: "7:50pm" },
      { month: "Jun", high: 87, low: 61, rainPct: 4, sunset: "8:08pm" },
      { month: "Jul", high: 95, low: 68, rainPct: 1, sunset: "8:06pm" },
      { month: "Aug", high: 95, low: 69, rainPct: 2, sunset: "7:40pm" },
      { month: "Sep", high: 90, low: 65, rainPct: 6, sunset: "6:59pm" },
      { month: "Oct", high: 83, low: 58, rainPct: 3, sunset: "6:18pm" },
      { month: "Nov", high: 71, low: 49, rainPct: 9, sunset: "5:49pm" },
      { month: "Dec", high: 63, low: 45, rainPct: 21, sunset: "5:45pm" },
    ],
  },
  "santa-monica": {
    miles: 38.6,
    travelFee: 0,
    bestEvening: "June through November",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 28,
    latestSunset: "8:07pm",
    latestSunsetMonth: "June",
    julyHigh: 81,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 46, rainPct: 19, sunset: "6:08pm" },
      { month: "Feb", high: 64, low: 45, rainPct: 19, sunset: "6:37pm" },
      { month: "Mar", high: 65, low: 47, rainPct: 28, sunset: "7:02pm" },
      { month: "Apr", high: 70, low: 51, rainPct: 8, sunset: "7:26pm" },
      { month: "May", high: 70, low: 54, rainPct: 5, sunset: "7:49pm" },
      { month: "Jun", high: 76, low: 58, rainPct: 2, sunset: "8:07pm" },
      { month: "Jul", high: 81, low: 61, rainPct: 1, sunset: "8:05pm" },
      { month: "Aug", high: 83, low: 62, rainPct: 3, sunset: "7:39pm" },
      { month: "Sep", high: 82, low: 62, rainPct: 6, sunset: "6:59pm" },
      { month: "Oct", high: 79, low: 57, rainPct: 3, sunset: "6:18pm" },
      { month: "Nov", high: 72, low: 50, rainPct: 8, sunset: "5:49pm" },
      { month: "Dec", high: 65, low: 46, rainPct: 20, sunset: "5:46pm" },
    ],
  },
  "temecula": {
    miles: 64.9,
    travelFee: 15,
    bestEvening: "May through November",
    bestLunch: "May through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 36,
    latestSunset: "8:00pm",
    latestSunsetMonth: "June",
    julyHigh: 90,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 44, rainPct: 21, sunset: "6:04pm" },
      { month: "Feb", high: 64, low: 43, rainPct: 27, sunset: "6:32pm" },
      { month: "Mar", high: 64, low: 46, rainPct: 36, sunset: "6:57pm" },
      { month: "Apr", high: 72, low: 50, rainPct: 17, sunset: "7:20pm" },
      { month: "May", high: 75, low: 53, rainPct: 11, sunset: "7:43pm" },
      { month: "Jun", high: 83, low: 58, rainPct: 4, sunset: "8:00pm" },
      { month: "Jul", high: 90, low: 63, rainPct: 1, sunset: "7:58pm" },
      { month: "Aug", high: 92, low: 65, rainPct: 2, sunset: "7:33pm" },
      { month: "Sep", high: 89, low: 64, rainPct: 6, sunset: "6:54pm" },
      { month: "Oct", high: 82, low: 56, rainPct: 7, sunset: "6:13pm" },
      { month: "Nov", high: 73, low: 48, rainPct: 11, sunset: "5:45pm" },
      { month: "Dec", high: 65, low: 45, rainPct: 20, sunset: "5:42pm" },
    ],
  },
  "thousand-oaks": {
    miles: 65.9,
    travelFee: 16,
    bestEvening: "May through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 25,
    latestSunset: "8:08pm",
    latestSunsetMonth: "June",
    julyHigh: 87,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 47, rainPct: 19, sunset: "6:09pm" },
      { month: "Feb", high: 63, low: 46, rainPct: 20, sunset: "6:38pm" },
      { month: "Mar", high: 63, low: 47, rainPct: 25, sunset: "7:04pm" },
      { month: "Apr", high: 71, low: 51, rainPct: 8, sunset: "7:27pm" },
      { month: "May", high: 72, low: 54, rainPct: 5, sunset: "7:51pm" },
      { month: "Jun", high: 79, low: 59, rainPct: 2, sunset: "8:08pm" },
      { month: "Jul", high: 87, low: 64, rainPct: 1, sunset: "8:06pm" },
      { month: "Aug", high: 88, low: 66, rainPct: 2, sunset: "7:41pm" },
      { month: "Sep", high: 85, low: 64, rainPct: 5, sunset: "7:01pm" },
      { month: "Oct", high: 80, low: 59, rainPct: 2, sunset: "6:19pm" },
      { month: "Nov", high: 72, low: 52, rainPct: 7, sunset: "5:51pm" },
      { month: "Dec", high: 64, low: 47, rainPct: 20, sunset: "5:47pm" },
    ],
  },
  "torrance": {
    miles: 33.1,
    travelFee: 0,
    bestEvening: "June through October",
    bestLunch: "April through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 26,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 76,
    januaryHigh: 63,
    months: [
      { month: "Jan", high: 63, low: 47, rainPct: 19, sunset: "6:08pm" },
      { month: "Feb", high: 63, low: 47, rainPct: 18, sunset: "6:37pm" },
      { month: "Mar", high: 63, low: 49, rainPct: 26, sunset: "7:02pm" },
      { month: "Apr", high: 67, low: 53, rainPct: 7, sunset: "7:25pm" },
      { month: "May", high: 69, low: 56, rainPct: 4, sunset: "7:48pm" },
      { month: "Jun", high: 73, low: 60, rainPct: 1, sunset: "8:06pm" },
      { month: "Jul", high: 76, low: 63, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 78, low: 64, rainPct: 2, sunset: "7:38pm" },
      { month: "Sep", high: 78, low: 64, rainPct: 5, sunset: "6:59pm" },
      { month: "Oct", high: 76, low: 58, rainPct: 2, sunset: "6:18pm" },
      { month: "Nov", high: 70, low: 51, rainPct: 7, sunset: "5:49pm" },
      { month: "Dec", high: 64, low: 48, rainPct: 18, sunset: "5:46pm" },
    ],
  },
  "west-covina": {
    miles: 9.2,
    travelFee: 0,
    bestEvening: "May through November",
    bestLunch: "May and October through November",
    hotMonths: "August",
    wettestMonth: "March",
    wettestPct: 31,
    latestSunset: "8:04pm",
    latestSunsetMonth: "June",
    julyHigh: 92,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 44, rainPct: 20, sunset: "6:06pm" },
      { month: "Feb", high: 66, low: 44, rainPct: 21, sunset: "6:35pm" },
      { month: "Mar", high: 67, low: 46, rainPct: 31, sunset: "7:00pm" },
      { month: "Apr", high: 75, low: 51, rainPct: 13, sunset: "7:23pm" },
      { month: "May", high: 78, low: 54, rainPct: 10, sunset: "7:47pm" },
      { month: "Jun", high: 85, low: 58, rainPct: 3, sunset: "8:04pm" },
      { month: "Jul", high: 92, low: 62, rainPct: 1, sunset: "8:03pm" },
      { month: "Aug", high: 94, low: 63, rainPct: 3, sunset: "7:37pm" },
      { month: "Sep", high: 91, low: 63, rainPct: 7, sunset: "6:57pm" },
      { month: "Oct", high: 84, low: 57, rainPct: 6, sunset: "6:16pm" },
      { month: "Nov", high: 75, low: 49, rainPct: 10, sunset: "5:47pm" },
      { month: "Dec", high: 66, low: 45, rainPct: 20, sunset: "5:44pm" },
    ],
  },
  "west-hollywood": {
    miles: 32.8,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 28,
    latestSunset: "8:06pm",
    latestSunsetMonth: "June",
    julyHigh: 85,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 45, rainPct: 18, sunset: "6:08pm" },
      { month: "Feb", high: 66, low: 45, rainPct: 18, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 47, rainPct: 28, sunset: "7:02pm" },
      { month: "Apr", high: 73, low: 51, rainPct: 8, sunset: "7:25pm" },
      { month: "May", high: 74, low: 54, rainPct: 7, sunset: "7:49pm" },
      { month: "Jun", high: 80, low: 59, rainPct: 2, sunset: "8:06pm" },
      { month: "Jul", high: 85, low: 61, rainPct: 1, sunset: "8:04pm" },
      { month: "Aug", high: 87, low: 63, rainPct: 3, sunset: "7:39pm" },
      { month: "Sep", high: 86, low: 62, rainPct: 6, sunset: "6:59pm" },
      { month: "Oct", high: 82, low: 57, rainPct: 3, sunset: "6:17pm" },
      { month: "Nov", high: 74, low: 49, rainPct: 8, sunset: "5:49pm" },
      { month: "Dec", high: 66, low: 46, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "whittier": {
    miles: 10.8,
    travelFee: 0,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 27,
    latestSunset: "8:05pm",
    latestSunsetMonth: "June",
    julyHigh: 88,
    januaryHigh: 65,
    months: [
      { month: "Jan", high: 65, low: 46, rainPct: 22, sunset: "6:07pm" },
      { month: "Feb", high: 67, low: 45, rainPct: 20, sunset: "6:36pm" },
      { month: "Mar", high: 67, low: 48, rainPct: 27, sunset: "7:01pm" },
      { month: "Apr", high: 74, low: 53, rainPct: 12, sunset: "7:24pm" },
      { month: "May", high: 76, low: 56, rainPct: 5, sunset: "7:47pm" },
      { month: "Jun", high: 82, low: 60, rainPct: 2, sunset: "8:05pm" },
      { month: "Jul", high: 88, low: 64, rainPct: 1, sunset: "8:03pm" },
      { month: "Aug", high: 89, low: 65, rainPct: 3, sunset: "7:37pm" },
      { month: "Sep", high: 88, low: 64, rainPct: 6, sunset: "6:57pm" },
      { month: "Oct", high: 83, low: 58, rainPct: 3, sunset: "6:16pm" },
      { month: "Nov", high: 74, low: 51, rainPct: 9, sunset: "5:48pm" },
      { month: "Dec", high: 66, low: 47, rainPct: 19, sunset: "5:45pm" },
    ],
  },
  "woodland-hills": {
    miles: 51.2,
    travelFee: 1,
    bestEvening: "April through November",
    bestLunch: "April through June and October through November",
    hotMonths: "",
    wettestMonth: "March",
    wettestPct: 27,
    latestSunset: "8:07pm",
    latestSunsetMonth: "June",
    julyHigh: 88,
    januaryHigh: 64,
    months: [
      { month: "Jan", high: 64, low: 47, rainPct: 19, sunset: "6:09pm" },
      { month: "Feb", high: 64, low: 46, rainPct: 19, sunset: "6:37pm" },
      { month: "Mar", high: 65, low: 47, rainPct: 27, sunset: "7:03pm" },
      { month: "Apr", high: 72, low: 52, rainPct: 12, sunset: "7:26pm" },
      { month: "May", high: 73, low: 53, rainPct: 8, sunset: "7:50pm" },
      { month: "Jun", high: 81, low: 59, rainPct: 2, sunset: "8:07pm" },
      { month: "Jul", high: 88, low: 63, rainPct: 1, sunset: "8:06pm" },
      { month: "Aug", high: 89, low: 64, rainPct: 2, sunset: "7:40pm" },
      { month: "Sep", high: 86, low: 63, rainPct: 6, sunset: "7:00pm" },
      { month: "Oct", high: 81, low: 59, rainPct: 3, sunset: "6:18pm" },
      { month: "Nov", high: 72, low: 52, rainPct: 8, sunset: "5:50pm" },
      { month: "Dec", high: 65, low: 47, rainPct: 20, sunset: "5:46pm" },
    ],
  },
}

export function getCityClimate(slug: string): CityClimate | undefined {
  return cityClimate[slug]
}
